# Generated by Django 4.2.7 on 2023-11-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_slug_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
