# Generated by Django 4.2.7 on 2023-11-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_blog_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="category",),
        migrations.AddField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
